name: Global CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  global-ci:
    uses: Ecrazye/automation/.github/workflows/reusable-ci.yml@main
    with:
      run_python: true
      run_node: true
      run_security: true
    secrets: inherit
